name: preflight-g7-db # You can also change this to another name to avoid warning with existing group.
services:
  frontend:
    container_name: pf-frontend-g7
    build: .
    ports:
      - ${NGINX_PORT}:5174
    networks:
      - pf-net
    environment:
      - NGINX_PROXY=${NGINX_PROXY}
      - NGINX_PORT=${NGINX_PORT}
networks:
  pf-net: # Check by using `docker network ls` command
    external: true
