name: preflight-g7-db
services:
  postgres:
    image: postgres:16-alpine
    container_name: pf-db-g7
    ports:
      - 5432:${POSTGRES_PORT}
    volumes:
      - pf-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - pf-net
volumes:
  pf-data:
networks:
  pf-net:
